services:
  sai-storage-mongo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6900:6900
      - 6901:6901
    depends_on:
      - mongo-db
    volumes:
      - ./config.json:/srv/config.json
  mongo-db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}