apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}-deploy
  namespace: ${NAMESPACE_NAME}-main
  labels:
    app: ${SERVICE_NAME}-main
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${SERVICE_NAME}-main
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}-main
    spec:
      containers:
      - name: ${SERVICE_NAME}-main-microservice
        image: ${IMAGE_NAME}
        ports:

